"""Regenerates tools/qr_fixtures.txt, the reference QR matrices that the
scenario `qr_encoder_matches_reference_matrices` checks scripts/QrEncoder.gd
against (issue #214).

The reference encoder is python-qrcode 8.2 (https://pypi.org/project/qrcode/,
BSD), forced to byte mode, and left to choose the version and the mask
itself -- so the fixture also checks that QrEncoder.gd's penalty scoring picks
the same mask.

    python -m venv venv && venv/bin/pip install qrcode==8.2
    venv/bin/python tools/gen_qr_fixtures.py > tools/qr_fixtures.txt
"""
import qrcode
from importlib.metadata import version

assert version("qrcode") == "8.2", version("qrcode")
LEVELS = {"L": qrcode.constants.ERROR_CORRECT_L, "M": qrcode.constants.ERROR_CORRECT_M}

CASES = [
    ("http://192.168.1.42:8080/", "M"),
    ("http://10.0.0.5:8080/", "M"),
    ("http://172.16.254.1:51234/", "M"),
    ("http://127.0.0.1:8080/", "M"),
    # The longest realistic join URL (issue #214 acceptance).
    ("http://255.255.255.255:65535/", "M"),
    ("http://255.255.255.255:65535/", "L"),
    ("http://192.168.1.42:8080/", "L"),
    # Longer than any join URL: multi-block versions 5-10, and version
    # information (version >= 7).
    ("http://192.168.100.200:8080/?room=" + "abcdefghij" * 5, "M"),
    ("http://192.168.100.200:8080/?room=" + "0123456789" * 14, "M"),
    ("http://192.168.100.200:8080/?room=" + "klmnopqrst" * 17, "L"),
]

print("# QR reference matrices for scripts/QrEncoder.gd (issue #214).")
print("# Generated by tools/gen_qr_fixtures.py with python-qrcode %s." % version("qrcode"))
print("# Each case: 'case<TAB>ecl<TAB>version<TAB>mask<TAB>text', then one line")
print("# per module row, '1' = dark, no quiet zone; a blank line ends it.")
for text, ecl in CASES:
    qr = qrcode.QRCode(error_correction=LEVELS[ecl], border=0)
    qr.add_data(qrcode.util.QRData(text.encode("utf-8"), mode=qrcode.util.MODE_8BIT_BYTE))
    qr.make(fit=True)  # picks the mask with best_mask_pattern()
    matrix = qr.get_matrix()
    mask = qr.best_mask_pattern()  # the same choice again, to print it
    print("case\t%s\t%d\t%d\t%s" % (ecl, qr.version, mask, text))
    for row in matrix:
        print("".join("1" if m else "0" for m in row))
    print()
